//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17020
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTLite.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GTLite.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _1291449967_security_high {
            get {
                object obj = ResourceManager.GetObject("1291449967_security-high", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1291732552_lock {
            get {
                object obj = ResourceManager.GetObject("1291732552_lock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ajax_loader {
            get {
                object obj = ResourceManager.GetObject("ajax_loader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GT Web Software|http://www.gt-web-software.webs.com/
        ///OpenWebKitSharp|http://code.google.com/p/open-webkit-sharp/
        ///The WebKit Open-Source Project|http://www.webkit.org/.
        /// </summary>
        internal static string BookmarksD {
            get {
                return ResourceManager.GetString("BookmarksD", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap CloseMask {
            get {
                object obj = ResourceManager.GetObject("CloseMask", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap find {
            get {
                object obj = ResourceManager.GetObject("find", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Form {
            get {
                object obj = ResourceManager.GetObject("Form", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap globe {
            get {
                object obj = ResourceManager.GetObject("globe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HistoryD {
            get {
                return ResourceManager.GetString("HistoryD", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon New_document {
            get {
                object obj = ResourceManager.GetObject("New_document", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon PrivateBrowsing {
            get {
                object obj = ResourceManager.GetObject("PrivateBrowsing", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html i18n-values=&quot;dir:textdirection&quot; dir=&quot;ltr&quot;&gt;&lt;head&gt;
        ///&lt;title i18n-content=&quot;title&quot;&gt;GTLite Navigator could not open this webpage&lt;/title&gt;
        ///&lt;style&gt;
        ///body {
        ///  background-color: #fff;
        ///  color: #000;
        ///  font-family: Helvetica, Arial, sans-serif;
        ///  font-size: 83%;
        ///  line-height: 120%;
        ///  max-width: 35em;
        ///  padding: 0.5em 1em;
        ///}
        ///li {
        ///  padding-bottom: .3em;
        ///}
        ///ul {
        ///  margin: .5em 0 0;
        ///  padding-bottom: 0;
        ///}
        ///h1 {
        ///  font-size: 1.5em;
        ///  margin-bottom: 1.5em;
        ///}
        ///h2 {
        ///  font-size: 1em;
        ///  font-weight:  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap wave_background {
            get {
                object obj = ResourceManager.GetObject("wave_background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
