// <auto-generated>
//     This code was generated by the .NET ToolStrip Customizer. Do not 
//     make any significant changes to this file, otherwise, it could not 
//     be opened within .NET ToolStrip Customizer.
// </auto-generated>

using System.Drawing;
using System.Windows.Forms;

namespace GTLite
{
    class GTLiteColorTable : ProfessionalColorTable
    {
        public override Color ButtonSelectedHighlight
        {
            get { return ButtonSelectedGradientMiddle; }
        }
        public override Color ButtonSelectedHighlightBorder
        {
            get { return ButtonSelectedBorder; }
        }
        public override Color ButtonPressedHighlight
        {
            get { return ButtonPressedGradientMiddle; }
        }
        public override Color ButtonPressedHighlightBorder
        {
            get { return ButtonPressedBorder; }
        }
        public override Color ButtonCheckedHighlight
        {
            get { return ButtonCheckedGradientMiddle; }
        }
        public override Color ButtonCheckedHighlightBorder
        {
            get { return ButtonSelectedBorder; }
        }
        public override Color ButtonPressedBorder
        {
            get { return ButtonSelectedBorder; }
        }
        public override Color ButtonSelectedBorder
        { 
            get { return Color.FromArgb(255, 179, 179, 179); }
        }
        public override Color ButtonCheckedGradientBegin
        { 
            get { return Color.FromArgb(255, 231, 228, 230); }
        }
        public override Color ButtonCheckedGradientMiddle
        { 
            get { return Color.FromArgb(255, 179, 179, 179); }
        }
        public override Color ButtonCheckedGradientEnd
        { 
            get { return Color.FromArgb(255, 193, 193, 193); }
        }
        public override Color ButtonSelectedGradientBegin
        { 
            get { return Color.FromArgb(255, 247, 244, 244); }
        }
        public override Color ButtonSelectedGradientMiddle
        { 
            get { return Color.FromArgb(255, 233, 233, 233); }
        }
        public override Color ButtonSelectedGradientEnd
        { 
            get { return Color.FromArgb(255, 189, 183, 184); }
        }
        public override Color ButtonPressedGradientBegin
        { 
            get { return Color.FromArgb(255, 210, 210, 210); }
        }
        public override Color ButtonPressedGradientMiddle
        { 
            get { return Color.FromArgb(255, 201, 199, 199); }
        }
        public override Color ButtonPressedGradientEnd
        { 
            get { return Color.FromArgb(255, 163, 163, 163); }
        }
        public override Color CheckBackground
        { 
            get { return Color.FromArgb(255, 255, 215, 166); }
        }
        public override Color CheckSelectedBackground
        { 
            get { return Color.FromArgb(255, 255, 215, 166); }
        }
        public override Color CheckPressedBackground
        { 
            get { return Color.FromArgb(255, 253, 170, 96); }
        }
        public override Color GripDark
        { 
            get { return Color.FromArgb(255, 111, 157, 217); }
        }
        public override Color GripLight
        { 
            get { return Color.FromArgb(255, 255, 255, 255); }
        }
        public override Color ImageMarginGradientBegin
        { 
            get { return Color.FromArgb(255, 233, 238, 238); }
        }
        public override Color ImageMarginGradientMiddle
        { 
            get { return Color.FromArgb(255, 233, 238, 238); }
        }
        public override Color ImageMarginGradientEnd
        { 
            get { return Color.FromArgb(255, 233, 238, 238); }
        }
        public override Color ImageMarginRevealedGradientBegin
        { 
            get { return Color.FromArgb(255, 233, 238, 238); }
        }
        public override Color ImageMarginRevealedGradientMiddle
        { 
            get { return Color.FromArgb(255, 233, 238, 238); }
        }
        public override Color ImageMarginRevealedGradientEnd
        { 
            get { return Color.FromArgb(255, 233, 238, 238); }
        }
        public override Color MenuStripGradientBegin
        { 
            get { return Color.FromArgb(255, 207, 203, 205); }
        }
        public override Color MenuStripGradientEnd
        { 
            get { return Color.FromArgb(255, 223, 223, 223); }
        }
        public override Color MenuItemSelected
        { 
            get { return Color.FromArgb(255, 225, 225, 225); }
        }
        public override Color MenuItemBorder
        { 
            get { return Color.FromArgb(255, 222, 220, 221); }
        }
        public override Color MenuBorder
        { 
            get { return Color.FromArgb(255, 133, 133, 133); }
        }
        public override Color MenuItemSelectedGradientBegin
        { 
            get { return Color.FromArgb(255, 243, 243, 243); }
        }
        public override Color MenuItemSelectedGradientEnd
        { 
            get { return Color.FromArgb(255, 223, 219, 221); }
        }
        public override Color MenuItemPressedGradientBegin
        { 
            get { return Color.FromArgb(255, 226, 239, 255); }
        }
        public override Color MenuItemPressedGradientMiddle
        { 
            get { return Color.FromArgb(255, 220, 218, 219); }
        }
        public override Color MenuItemPressedGradientEnd
        { 
            get { return Color.FromArgb(255, 185, 185, 185); }
        }
        public override Color RaftingContainerGradientBegin
        { 
            get { return Color.FromArgb(255, 255, 255, 255); }
        }
        public override Color RaftingContainerGradientEnd
        { 
            get { return Color.FromArgb(255, 255, 255, 255); }
        }
        public override Color SeparatorDark
        { 
            get { return Color.FromArgb(255, 157, 201, 255); }
        }
        public override Color SeparatorLight
        { 
            get { return Color.FromArgb(255, 255, 255, 255); }
        }
        public override Color StatusStripGradientBegin
        { 
            get { return Color.FromArgb(255, 227, 239, 255); }
        }
        public override Color StatusStripGradientEnd
        { 
            get { return Color.FromArgb(255, 177, 211, 255); }
        }
        public override Color ToolStripBorder
        { 
            get { return Color.FromArgb(255, 111, 157, 217); }
        }
        public override Color ToolStripDropDownBackground
        { 
            get { return Color.FromArgb(255, 246, 246, 246); }
        }
        public override Color ToolStripGradientBegin
        { 
            get { return Color.FromArgb(255, 227, 239, 255); }
        }
        public override Color ToolStripGradientMiddle
        { 
            get { return Color.FromArgb(255, 239, 237, 238); }
        }
        public override Color ToolStripGradientEnd
        { 
            get { return Color.FromArgb(255, 193, 193, 193); }
        }
        public override Color ToolStripContentPanelGradientBegin
        { 
            get { return Color.FromArgb(255, 232, 230, 231); }
        }
        public override Color ToolStripContentPanelGradientEnd
        { 
            get { return Color.FromArgb(255, 163, 163, 163); }
        }
        public override Color ToolStripPanelGradientBegin
        { 
            get { return Color.FromArgb(255, 191, 219, 255); }
        }
        public override Color ToolStripPanelGradientEnd
        { 
            get { return Color.FromArgb(255, 191, 219, 255); }
        }
        public override Color OverflowButtonGradientBegin
        { 
            get { return Color.FromArgb(255, 215, 232, 255); }
        }
        public override Color OverflowButtonGradientMiddle
        { 
            get { return Color.FromArgb(255, 167, 204, 251); }
        }
        public override Color OverflowButtonGradientEnd
        { 
            get { return Color.FromArgb(255, 111, 157, 217); }
        }
    }
}